# on 이후 Actions가 어떻게 작동할지를 정의합니다. 
# workflow_dispatch: 이하는 main 브랜치의 푸시로 작동합니다. 
# schedule: 이하는 정의된 주기적으로 작동합니다.
on:
  workflow_dispatch:    
  push:
    branches: main
  #schedule:
    #- cron: '*/30 * * * *' # 매 30분마다 실행
    #- cron: '* */3 * * *' # 매 3시간마다 실행
    # 실제 스케쥴 작업이 시작될 cron을 등록하면 됩니다.
    # 크론은 https://crontab.guru/ 여기서 확인하면 좋을 것 같습니다.


name: Quarto

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
#
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
#
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      #- run: pip install jupyter
      - run: pip install -r requirements.txt
#      
      - name: publish
        uses: quarto-dev/quarto-actions/publish@v2
        with: 
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
#    
